<?php
declare(strict_types=1);
require __DIR__ . '/SQLiteHarness.php';
require __DIR__ . '/bootstrap.php';
require __DIR__ . '/scenarios.php';
require __DIR__ . '/controller.php';
require __DIR__ . '/import-runs.php';
require __DIR__ . '/uploads.php';
require __DIR__ . '/recovery.php';
require __DIR__ . '/locator.php';
require __DIR__ . '/albums.php';
require __DIR__ . '/album-controller.php';
require __DIR__ . '/adapter.php';
require __DIR__ . '/membership-command.php';
require __DIR__ . '/album-selection.php';
require __DIR__ . '/namespace.php';

$pdo = new PDO('sqlite::memory:');
$schema = new TestHarness\Schema();
$migration = new OCA\ApplePhotosConnector\Migration\Version008000Date20260910000000();
$migration->changeSchema(new class implements OCP\Migration\IOutput {}, fn () => $schema, []);
$contentMigration = new OCA\ApplePhotosConnector\Migration\Version008600Date20260918000000(new TestHarness\Connection($pdo));
$contentMigration->changeSchema(new class implements OCP\Migration\IOutput {}, fn () => $schema, []);
$inventoryV2Migration = new OCA\ApplePhotosConnector\Migration\Version008800Date20260925000000();
$inventoryV2Migration->changeSchema(new class implements OCP\Migration\IOutput {}, fn () => $schema, []);
$schema->apply($pdo);
$contentMigration->postSchemaChange(new class implements OCP\Migration\IOutput {}, fn () => $schema, []);
require __DIR__ . '/fresh-install.php';
freshInstallScenarios();
scenarios(new OCA\ApplePhotosConnector\Db\InventoryRepository(new TestHarness\Connection($pdo)));
controllerScenarios(new OCA\ApplePhotosConnector\Db\InventoryRepository(new TestHarness\Connection($pdo)));
runScenarios(new OCA\ApplePhotosConnector\Db\InventoryRepository(new TestHarness\Connection($pdo)));
runFailureScenarios(new TestHarness\Connection($pdo));
uploadScenarios(new OCA\ApplePhotosConnector\Db\InventoryRepository(new TestHarness\Connection($pdo)));
uploadRollbackScenario(new TestHarness\Connection($pdo));
recoveryScenarios(new OCA\ApplePhotosConnector\Db\InventoryRepository(new TestHarness\Connection($pdo)));
locatorScenarios();
albumScenarios();
albumControllerScenarios($pdo);
adapterScenarios(new OCA\ApplePhotosConnector\Db\AlbumMapRepository(new TestHarness\Connection($pdo)));
albumSyncDiagnosticControllerScenario();
albumRecoveryOrchestratorScenario(new TestHarness\Connection($pdo),$pdo);
explicitAlbumSelectionOrchestratorScenario(new TestHarness\Connection($pdo),$pdo);
membershipCommandScenarios();
albumSelectionScenarios();
check(true, "F12: existing PHP regression suite passes on fresh schema");
require __DIR__ . '/retarget.php';
require __DIR__ . '/ticket-lifecycle.php';
retargetScenarios();
ticketLifecycleScenarios();
retargetRaceScenario();
require __DIR__ . '/historical-reservations.php';
historicalReservationScenarios();
require __DIR__ . '/content-identities.php';
contentIdentityScenarios();
require __DIR__ . '/inventory-idempotency.php';
inventoryIdempotencyScenarios($pdo);
inventoryIdempotencyConcurrencyScenario();
echo "All standalone SQLite tests passed.\n";
